.babelrc
.gitignore
karma.conf.js
package.json
test/.eslintrc

Changes:
- add sinon framework for spies, stubs, &c
- add test coverage reporting
- change `npm run karma-watch` command to `npm run test-watch`
Ping @jh-bate

test tooling updates

---

.gitignore
package.config.js
package.json

OK, here it is @krystophv 
I created a separate config that just builds on the main one a little to keep it cleaner for making changes in the main config as far as loaders. We *do* use the main config for React Storybook.
The main thing that's confusing me a bit is that two copies of React problem is still an issue. I would have that defining React as an `external` would have solved that, but I guess when webpack resolves the dependency, it still looks in the "closest" `node_modules` dir? Not an issue since you may have found another solution to that, just adds to my lack of confidence that I got things right here...
In terms of merge order, this should be merged along with [tideline #283](https://github.com/tidepool-org/tideline/pull/283) and [blip …

use webpack with "library" options for build

---

src/containers/trends/CBGSlicesAnimationContainer.js
src/utils/trends/data.js
test/utils/trends/data.test.js

What it says on the tin. (Before slicing was > start and <= end which is a bit unintuitive although it usually doesn't matter, but for Animas data with only minute resolution where you actually get data points on the border between slices, it matters.)
For your reviewing pleasure, @jh-bate or @krystophv

ensure time binning is >= start and < end for each slice

---

.npmignore
README.md
package.config.js
package.json

My borking of the merge conflicts on package.json when I was trying to do some simple branch updating clued me in to some mis-categorized dependencies added for the settings work, so that is fixed here.
The tl;dr is: whenever you add a dependency that is used in actual viz code (not tests or tooling), ask yourself: "Is this also a dependency of blip?" (e.g., React)
- YES -> it goes in `devDependencies` **and** `peerDependencies` **and** gets added as an "external" in package.config.js
- NO -> it goes in `dependencies` **and** gets added as an "external" in package.config.js
I have also tried to explain this a bit in the README and would like it if everyone could take a look and LMK if it's clear and if we all understand: ping @krystophv @hntrdglss @jh-bate 
I could go into a lot more …

deps cleanup

---

src/components/settings/animas/Animas.css
src/components/settings/medtronic/Medtronic.css
src/components/settings/omnipod/Omnipod.css
src/components/settings/tandem/Tandem.css

because, ya know, you only want the one body tag, not the other ones.
This prevents the scrollbar enforcement from bleeding over into the annotation tooltips in blip due to the foreignObject having a `body` tag, which of course is not a direct descendent of an `html` tag.

more specific body css selector

---

package.json
src/components/settings/common/SingleLineCollapsibleContainerLabel.js
test/components/settings/nontandem/NonTandem.test.js
test/components/settings/tandem/Tandem.test.js

Another thing I noticed while working on my next device settings task - the 'Active on upload' text got dropped by accident for Tandem.
Review first thing if you can @hntrdglss?

restore 'Active on upload' text for Tandem + regression tests

---

data/pumpSettings/animas/flatrate.json
data/pumpSettings/animas/multirate.json
data/pumpSettings/medtronic/flatrate.json
data/pumpSettings/medtronic/multirate.json
data/pumpSettings/omnipod/flatrate.json
data/pumpSettings/tandem/flatrate.json
package.json
src/components/settings/common/Header.js
src/components/settings/nontandem/NonTandem.js
src/components/settings/tandem/Tandem.js
src/utils/settings/data.js
src/utils/settings/factory.js
test/components/settings/common/Header.test.js
test/components/settings/nontandem/NonTandem.test.js
test/components/settings/tandem/Tandem.test.js
test/utils/settings/data.test.js

Discovered a regression (missing 'Active at upload' text for MedT) after briefly deploying blip v0.14.11 to prd before the offsite. (Rolled back to v0.14.8 after discovering it.)
The root cause of the dropped 'Active at upload' text was basically some incorrect fixture data for `pumpSettings` with capitalized basal schedule names (which **never** happens with MedT pumps in the wild because basal schedule names are not under user control). This masked how adding capitalization to MedT broke the logic to detect matching between each schedule name at the active schedule. So this PR fixes the underlying data fixtures and (after consultation with BA) only capitalizes MedT basal schedule names and preserves user-controlled capitalization on other pumps (tests have been added to prove this). …

fix MedT active at upload regression

---

package.json
src/components/settings/nontandem/NonTandem.js
src/components/settings/tandem/Tandem.js
src/utils/settings/factory.js

Here's the fix for the latest regression on the device settings work - just failed to factor out one piece of device-specific information, which is how the data is accessed for each of the different non-Tandem varieties of BG target.

device settings bgTarget data regression

---

src/components/common/tooltips/Tooltip.css
src/components/common/tooltips/Tooltip.js
src/components/trends/smbg/FocusedSMBGPointLabel.js
src/components/trends/smbg/FocusedSMBGRangeLabels.js
stories/components/common/tooltips/Tooltip.js
test/components/common/tooltip/Tooltip.test.js
test/components/trends/cbg/RangeSelect.test.js

The changes here add four main features to the Tooltip component:
- the Tooltips are now invisible to pointer events, to avoid "stuttering" if connection between the original hover target and the pointer is broken due to hovering on a bit of the tooltip itself!
- the total offset gets recalculated from new props if the component is updated (via the `componentWillReceiveProps` lifecycle hook)
- ability to pass in a `backgroundColor` in props
- ability to pass in a `horizontal` instead of `left` in the `offset` prop: if/when you do this, the calculated total offset will flip the sign of the value specified in `horizontal` when the tooltip is on the left...this avoids repeating [logic such as found here](https://github.com/tidepool-org/viz/blob/master/src/components/trends/smbg/FocusedSMBGPoi …

Tooltip component updates

---

src/components/trends/common/Background.css
src/components/trends/common/Background.js
src/containers/trends/TrendsSVGContainer.js
src/styles/colors.css
stories/components/trends/common/Background.js
test/components/trends/common/Background.test.js
test/containers/trends/TrendsSVGContainer.test.js

Here's a very small PR just containing the styling changes to the chart background for Trends view—that is, new colors and removal of the lighter target range area.
This is quite independent of #38 (thought I suppose both make changes to the TrendsSVGContainer, but the conflicts should be small if present as all) so can be reviewed and merged into the feature branch (merge target) in any order.

updates to Trends view chart background

---

src/components/trends/common/NoData.js
src/containers/trends/TrendsContainer.js
src/containers/trends/TrendsSVGContainer.js
test/components/trends/common/NoData.test.js
test/containers/trends/TrendsSVGContainer.test.js

A small addition to the Trends work. I noticed that if the user unselected all days of the week, the no data message didn't make a lot of sense (since it talks about no data in the time period). At our meeting yesterday, new language was proposed for this case.
I thought this would be a nice small one for @hntrdglss to look at, and I've targeted it to the branch for #40 to keep the diff limited to the new changes. (It builds on the reorg of rendering the `NoData` component in that earlier work.)

render a different no data message when all days unselected

---

package.json
src/components/trends/cbg/CBGDateTraceAnimated.css
src/components/trends/cbg/CBGDateTraceAnimated.js
src/components/trends/cbg/CBGSliceAnimated.css
src/components/trends/cbg/FocusedCBGSliceSegment.css
src/components/trends/cbg/FocusedCBGSliceSegment.js
src/containers/trends/CBGDateTracesAnimationContainer.js
src/containers/trends/TrendsSVGContainer.js
src/utils/trends/data.js
test/components/trends/cbg/CBGDateTraceAnimated.test.js
test/components/trends/cbg/FocusedCBGSliceSegment.test.js
test/containers/trends/CBGDateTracesAnimationContainer.test.js
test/containers/trends/TrendsSVGContainer.test.js
test/utils/trends/data.test.js

This adds a bunch of new components (and tests for them) so that when you hover on one of the five segments of a cbg slice in the CGM version of Trends view, all the sensor traces for the dates that intersect with that segment appear on top of the slices display.
I didn't put any tests around the special animation lifecycle methods (added by `TransitionGroupPlus`) where we're doing the GSAP-based animation because it seemed like any testing there would basically be either testing `TransitionGroupPlus` or GSAP itself, not our code... LMK if you feel differently.

show cbg date traces on segment hover

---

src/components/trends/smbg/SMBGDateLineAnimated.js
src/components/trends/smbg/SMBGDatePointsAnimated.js
src/containers/trends/SMBGsByDateContainer.js
src/containers/trends/TrendsContainer.js
src/containers/trends/TrendsSVGContainer.js
test/components/trends/smbg/SMBGDateLineAnimated.test.js
test/components/trends/smbg/SMBGDatePointsAnimated.test.js
test/containers/trends/TrendsContainer.test.js
test/containers/trends/TrendsSVGContainer.test.js

Since I have to reorg a bunch of my work I was able to separate out this cleanup as a tiny PR. Just more consistency fixes to ensure we always use "date" to talk about a YYYY-MM-DD date of data, not "day" (which we use for Mon, Tues, etc.).
Another quickie for @hntrdglss or @krystophv

day to date renaming

---

src/components/trends/common/FocusedRangeLabels.js
src/components/trends/smbg/FocusedSMBGPointLabel.js
src/containers/trends/CBGSlicesContainer.js
src/containers/trends/SMBGRangeAvgContainer.js
src/utils/bloodglucose.js
src/utils/constants.js
src/utils/format.js
src/utils/trends/data.js
test/utils/bloodglucose.test.js
test/utils/constants.test.js
test/utils/format.test.js
test/utils/trends/data.test.js

This change set is more complex than I anticipated. Would be interested in feedback to simplify it, but I'm not sure that's possible.
The root of the problem is that we were showing things like this in Trends, surfacing a fake 39 value (really Low Dexcom data):
Just as we do in e.g., the Daily view, this should show with 'Low' instead:
(We use the two-letter abbreviations 'Lo' and 'Hi' due to size constraints in the round tooltips on Daily view but will be phasing that out.)
The complication comes in with the fact that on Trends where we are showing *aggregate* data and not surfacing values from individual data points, we may have data from more than one device present (especially on the BGM side) and different devices have different out-of-range value thresholds.
So the general approach …

handle display of out-of-range BGs on Trends

---

src/components/trends/cbg/CBGSliceAnimated.css
src/components/trends/common/FocusedRangeLabels.js
src/components/trends/smbg/FocusedSMBGPointLabel.js
src/containers/trends/CBGSlicesContainer.js
src/containers/trends/SMBGRangeAvgContainer.js
src/containers/trends/TrendsContainer.js
src/redux/reducers/trendsStateByUser.js
src/styles/colors.css
src/utils/bloodglucose.js
src/utils/constants.js
src/utils/format.js
src/utils/trends/data.js
test/containers/trends/TrendsContainer.test.js
test/redux/reducers/trendsStateByUser.test.js
test/utils/bloodglucose.test.js
test/utils/constants.test.js
test/utils/format.test.js
test/utils/trends/data.test.js

This should be the final PR for the current Trends feature changes, contains a few styling tweaks/fixes and a substantive bugfix for "stuck" hover labels after clicking thru to Daily and then back to Trends, which I solved by clearing all focused state on `componentWillUnmount`.
Stacked on #53 again for diffing convenience.

Trends misc tweaks

---

package.json
src/components/trends/cbg/CBGSliceAnimated.css
src/components/trends/common/FocusedRangeLabels.js
src/components/trends/smbg/FocusedSMBGPointLabel.js
src/components/trends/smbg/SMBGMean.js
src/components/trends/smbg/SMBGMeanAnimated.css
src/components/trends/smbg/SMBGMeanAnimated.js
src/components/trends/smbg/SMBGRangeAnimated.css
src/containers/trends/CBGSlicesContainer.js
src/containers/trends/SMBGRangeAvgContainer.js
src/containers/trends/TrendsContainer.js
src/containers/trends/TrendsSVGContainer.js
src/redux/reducers/trendsStateByUser.js
src/styles/colors.css
src/utils/bloodglucose.js
src/utils/constants.js
src/utils/format.js
src/utils/trends/data.js
test/components/trends/smbg/SMBGMean.test.js
test/components/trends/smbg/SMBGMeanAnimated.test.js
test/containers/trends/TrendsContainer.test.js
test/containers/trends/TrendsSVGContainer.test.js
test/redux/reducers/trendsStateByUser.test.js
test/utils/bloodglucose.test.js
test/utils/constants.test.js
test/utils/format.test.js
test/utils/trends/data.test.js

Replaces #52 with a clean change (specifying a working version for `jsx-ast-utils` in our package.json) for the build problem.
The companion to [blip #383](https://github.com/tidepool-org/blip/pull/383).
Various changes:
- bring back mean rectangle + tests
- same fades in & out on range rect and mean fill as on CGM side when indiv smbg(s) focused
- wider range box with new styling
I've stacked this on #51 for easy diffing.

Trends BGM changes

---

src/utils/bolus.js
test/utils/bolus.test.js

This is a port of tideline's js/plot/util/commonbolus.js which basically maps the bolus data model onto the concepts used for rendering boluses - things like getting the total programmed dose, the total recommended dose, etc.

port bolus logic

---

src/index.js
src/utils/bloodglucose.js
test/utils/bloodglucose.test.js

This was being done in trends.js in Blip, and I'll need it now for the print view, so factored it out and made a separate branch since it's just a util that can come into master at any time.

refactor util to reshape tideline-style bgClasses to viz-style bgBounds

---

docs/DirectoryStructure.md
docs/deps/React.md
src/components/settings/common/PumpSettingsContainer.js
src/components/trends/cbg/CBGDateTracesAnimationContainer.js
src/components/trends/cbg/CBGSlicesContainer.js
src/components/trends/common/TrendsContainer.js
src/components/trends/common/TrendsSVGContainer.js
src/components/trends/smbg/SMBGRangeAvgContainer.js
src/components/trends/smbg/SMBGsByDateContainer.js
src/index.js
test/components/settings/common/PumpSettingsContainer.test.js
test/components/trends/cbg/CBGDateTracesAnimationContainer.test.js
test/components/trends/cbg/CBGSlicesContainer.test.js
test/components/trends/common/TrendsContainer.test.js
test/components/trends/common/TrendsSVGContainer.test.js
test/components/trends/smbg/SMBGRangeAvgContainer.test.js
test/components/trends/smbg/SMBGsByDateContainer.test.js

I based this off #71 for expediency, but I'd review that first @krystophv to keep the diff sane. I've done a fair amount of running this locally to prove to myself that the reorganization hasn't broken anything, so I'm fairly confident we're good to go here.

get rid of src/containers/ in favor of everything in src/components/

---

data/bolus/fixtures.js
src/components/common/data/Bolus.css
src/components/common/data/Bolus.js
src/modules/render/bolus.js
src/styles/colors.css
src/styles/diabetes.css
src/utils/bolus.js
stories/components/common/data/Bolus.js
test/components/common/data/Bolus.test.js
test/helpers/scales.js
test/modules/render/bolus.test.js
test/utils/bolus.test.js

This is a port of tideline's bolus rendering (pretty much [this file](https://github.com/tidepool-org/tideline/blob/master/js/plot/util/drawbolus.js) and the filtering in [this one](https://github.com/tidepool-org/tideline/blob/master/js/plot/wizard.js)).
Still to come: the carb circles on calculator-accompanied ("wizard") insulin events. I thought this was enough to review for now.
The most important things to review here are the additions to the bolus utilities and the actual path generation. There is also a React component (& tests) to render bolus paths in SVG on the web for Storybook purposes (at present). The commits are fairly logically grouped sets of changes, but some may still be large sets of changes.
LMK if you have any questions of would like a walk-through @krystophv

render target agnostic bolus rendering

---

README.md
package.json

See [this Travis build for blip](https://travis-ci.org/tidepool-org/blip/jobs/228490914) where Yarn failed out due to viz specifying a node engine of 6.x.
This is a dependency for [blip #414](https://github.com/tidepool-org/blip/pull/414).

relax node engine to avoid Yarn install failures

---

src/components/common/data/Bolus.css
src/modules/render/bolus.js
src/styles/colors.css
src/styles/diabetes.css
src/utils/bloodglucose.js
src/utils/bolus.js
src/utils/datetime.js
src/utils/format.js
test/utils/bloodglucose.test.js
test/utils/bolus.test.js
test/utils/datetime.test.js
test/utils/format.test.js

There are two things here: some small tweaks to the bolus rendering for greater render-target-agnostic behavior (after trying things out in print view)... The key here is to define all paths explicitly as shapes even if just drawing a line because of the variability across render targets for how stroke is positioned on a path. (Yes, it varies, sadly.)
Then I pulled over more of the utilities I've had to add in the print view work, including a backwards-compatible change to the existing `classifyBgValue`.
Would recommend going through this PR commit by commit @krystophv

bolus rendering tweaks + more ddata utils adds

---

data/bolus/fixtures.js
src/components/common/data/Bolus.css
src/components/common/data/Bolus.js
src/styles/colors.css
src/styles/diabetes.css
test/components/common/data/Bolus.test.js

Another small addition building on the last PR (#78).
Note that I've chosen to add the rendering for the web SVG target independently of the print view here. While it would be possible to do the circles with a path generator, it's not possible to do the text label that way, so some code would have to be reimplemented across print view and web SVG rendering anyway, and circles are easy, so might as well just reimplement both rather than have a confusing (IMO) mix of circle rendered via the path generator and label rendered in the native code.

render carb circles & labels for wizards

---

SUMMARY.md
docs/StartHere.md
docs/misc/CommonProps.md
docs/misc/README.md

Just realized adding the datetime docs in viz (which I'd planned to go along with this small doc) doesn't make sense because datetime stuff is also relevant to the uploader, so I separated out that stuff for a PR to the docs repo.
This is just a bit of additional quick ref documentation for `bgPrefs` and `timePrefs` props. I'll tag @cbwebdevelopment for review and we can discuss the review process before you do so :)

document common props

---

package.json
src/components/trends/smbg/FocusedSMBGPointLabel.js
src/modules/print/DailyPrintView.js
src/utils/bloodglucose.js
src/utils/print/data.js
test/utils/bloodglucose.test.js
test/utils/print/data.test.js

For CBG values, we show a HI/LO tooltip when the value is out of range. For SMBG values, we show value +1/-1 the threshold, e.g. when the threshold is 600 the value would be 601, and an annotation to indicate that the actual value can be higher or lower. 
We want CBG and SMBG values to have the same behaviour, ie., both should show 'High/Low' text (CBG text to be truncated to 'Hi/Lo' to fit into small tooltip circle.
Full details on trello: https://trello.com/c/p7L3RoNn
Goes hand-in-hand with https://github.com/tidepool-org/tideline/pull/321

Fix for displaying inaccurate 'High' and 'Low' smbg values

---

Dockerfile

Goes hand-in-hand with:
https://github.com/tidepool-org/tools/pull/64
https://github.com/tidepool-org/blip/pull/451
Changes to Dockerfile to allow us to not volume-mount the `node_modules` and `dist` directories to improve local performance.

Only volume-mount the bare minimum of files docker image.

---

src/components/trends/smbg/FocusedSMBGPointLabel.js
test/components/trends/smbg/FocusedSMBGPointLabel.test.js

Prior to this fix, hovering on a BGM in default dev tools on mode (with the Redux state mutation tracker) would crash the app when hovering on a BGM in the BGM version of Trends view:
The change I've made here is to make sure to clone the `allSmbgsOnDate` and `allPositions` arrays (via `.slice()`) in `<FocusedSMBGPointLabel/>` prior to mutating them.
Just a small little fix 🙂

bugfix for Redux state mutation violation (crashes app in dev mode)

---

data/types.js
package.json
src/components/trends/common/TrendsContainer.js
src/utils/basics/data.js
src/utils/bloodglucose.js
src/utils/constants.js
test/components/trends/common/TrendsContainer.test.js
test/utils/basics/data.test.js
test/utils/bloodglucose.test.js
test/utils/constants.test.js

Libre CBG data is not being calculated in a number of locations due to having an insufficient number of data points collected in a day.
This is because the minimum data thresholds are all based on getting a certain percentage of the day covered, based on getting a new reading every 5 minutes.  The Libre, however, only gets readings every 15 minutes, so we have to reduce the minimum amount of readings expected for Libre data threefold.
This PR includes fixes for the BG distribution widget in the Basics print view, and properly defaulting to cbg data in the trends view when data is sufficient.
See https://trello.com/c/FNlDqd1A for details.
Goes hand-in-hand with:
https://github.com/tidepool-org/blip/pull/458
https://github.com/tidepool-org/tideline/pull/326

Libre data not being calculated due to insufficient data points

---

package.json
src/components/common/tooltips/Tooltip.css
src/components/common/tooltips/Tooltip.js
src/components/daily/bolustooltip/BolusTooltip.css
src/components/daily/bolustooltip/BolusTooltip.js
src/index.js
src/styles/colors.css
src/utils/bolus.js
stories/components/common/tooltips/Tooltip.js
stories/components/daily/BolusTooltip.js
test/components/daily/BolusTooltip.test.js
test/utils/bolus.test.js

Adds a new bolus tooltip which will display all relevant information concerning a bolus.
See also:
blip: https://github.com/tidepool-org/blip/pull/457
tideline: https://github.com/tidepool-org/tideline/pull/325

Bolus tooltips

---

package.json
src/components/daily/bolustooltip/BolusTooltip.js

See https://trello.com/c/OKj6Qyji for details.
Related PRs:
tidepool-org/tideline#338
tidepool-org/blip#480
This PR is required due to a side effect of a rounding fix applied to the tideline PR in the nurseshark plugin that was rounding the BG values when converting from the stored `mmol/L` values to `mg/dL` prior to categorization.  
This caused the `mg/dL` values in the bolus tooltips to show numerous decimal places.  This PR performs the missing formatting in the component render methods.

Update glucose defaults to reflect standards

---

package.json
src/utils/basics/data.js
test/utils/basics/data.test.js

See https://trello.com/c/NFKNjxyT for details.
Related PRs:
https://github.com/tidepool-org/blip/pull/494
https://github.com/tidepool-org/tideline/pull/347

Add Basal:Bolus ratio to basics view for Automated Basal devices

---

package.json
src/components/daily/smbgtooltip/SMBGTooltip.css
src/utils/annotations.js
test/components/daily/SMBGTooltip.test.js
test/utils/annotations.test.js

See: https://trello.com/c/u8Fid7Hi/439-600-series-bug-remove-calibration-yes-annotation
blip PR: https://github.com/tidepool-org/blip/pull/501

Remove calibration related annotation messages for 600 series

---

package.json
src/utils/format.js
stories/components/daily/BolusTooltip.js
test/utils/format.test.js

Some pumps allow for boluses at 0.025 unit intervals and we shouldn't be rounding them if they're provided in that level of precision.
blip PR: https://github.com/tidepool-org/blip/pull/502
Trello: https://trello.com/c/9ET8Bmh5/146-setting-6-series-bolus-increment-to-025-causes-loss-of-precision-due-to-rounding

Add thousandths precision to insulin formatting

---

data/types.js
package.json
src/components/daily/foodtooltip/FoodTooltip.css
src/components/daily/foodtooltip/FoodTooltip.js
src/index.js
src/utils/data.js
test/components/daily/FoodTooltip.test.js
test/utils/data.test.js

Adds a FoodTooltip which largely mimics the existing tooltip components, if just a little simplified for now as we _only_ have/are concerned with displaying carbohydrate data from an otherwise potentially very complex datatype (`food`). Also modifies `getCarbsData` to take the new `food` datatype into account.
Pairs well with:
tideline: https://github.com/tidepool-org/tideline/pull/365
blip: https://github.com/tidepool-org/blip/pull/537
Trello: https://trello.com/c/0WUNaQS6

Carb rendering

---

package.json
src/components/common/stat/BgBar.js
test/components/common/stat/BgBar.test.js

See https://trello.com/c/YcHZj4dI for details
Goes with:
tidepool-org/blip#549
Fix is twofold:
1. The actual error was resulting from the `classifyBgValue` utility function being called with a negative value during the BgBar component render. This PR ensures that only a positive, numeric value is passed in, which avoids the thrown error.
2. In cases where there are extremely wide deviation, it was possible that the high and low "bars" on the bg scale would actually render beyond the scale limits.  The rendered bar x positions are now constrained to the scale limits.

Tidepool web crashes when rendering SD stat widget when SD > mean

---

package.json
src/components/trends/common/TrendsContainer.js
test/components/trends/common/TrendsContainer.test.js
yarn.lock

See https://trello.com/c/EnbpV4VY for details.
Also, includes a minor patch version upgrade to `lodash`, which included a fix for a security vulnerability (though not one that was critical or exploitable in our app).
See also tidepool-org/blip#552

Fix Y-Axis bg tick overlaps on Trends view

---

package.json
src/components/common/loader/Loader.css
src/components/common/loader/Loader.js
src/components/common/stat/Stat.js
test/components/common/stat/Stat.test.js

https://trello.com/c/kiGrj7Oo
The main fix was to ensure that the CSS loading dot animations are only happening while visible.
The other fix is a workaround for the time being, allowing the the stat animations to be disabled via a `animateStats=false` query param.
Related PR: tidepool-org/blip#586

Reduce idle cpu usage on data views

---

package.json
src/components/common/tooltips/Tooltip.js
test/components/common/tooltip/Tooltip.test.js

Having the tooltips update the offset state in `componentDidUpdate`, while done in a way that should have prevented infinite render loops (was only called within a conditional as noted at https://reactjs.org/docs/react-component.html#componentdidupdate), it seems that in some difficult-to-reproduce circumstances, this was in fact occurring for 2 of our team members.
This fix removes the state update within `componentDidUpdate` and instead calls the `calculateOffset` method a second time in `componentDidMount` within a `requestAnimationFrame` block.  This still allows the correct positioning to be applied after browser reflow and before browser repaint, which ensures that the initial rendering is in the correct positioning, which was the original reason for the state update in …

Tooltip hover fix [WEB-165]

---

webpack.config.js

It's at times important to have `viz` compile with a more detailed source map for debugging (at the expense of slower compile times), which this PR enables via an environment variable
Part of [WEB-210] 
[WEB-210]: https://tidepool.atlassian.net/browse/WEB-210

Allow updating devtool source map mode with environment variable [WEB-210] 

---

package.json
src/utils/DataUtil.js
test/utils/DataUtil.test.js

Also stores a copy of the `time` and `deviceTime` fields in their original ISO date string format for easier date inference (vs. deciphering a unix timestamp)
See [WEB-732] for details.
Goes with tidepool-org/blip#649
[WEB-732]: https://tidepool.atlassian.net/browse/WEB-732

[WEB-732] Allow returning raw data for debugging.

---

package.json
src/utils/DataUtil.js
stories/data/DataUtil.js
test/utils/DataUtil.test.js

Fixes [WEB-743]
Also noticed that the nested bolus/wizards weren't necessarily including all the appropriate fields, so includes a fix for those as well (even though I don't think it was actually causing a bug in our usage)
Related PR: tidepool-org/blip#659
[WEB-743]: https://tidepool.atlassian.net/browse/WEB-743

[WEB-743] Fix suppressed basal normalized output

---

package.json
src/utils/DataUtil.js
test/utils/DataUtil.test.js

See [WEB-805] for details.
The issue was that the fill data wasn’t being generated for users viewing data from a time zone that had GMT offsets that didn’t fall squarely on the hour, such as Asia/Kolkata in this case, with an offset of GMT + 5h30m, or Canada/Newfoundland, which is GMT - 3h30m.  This missing fill data was causing a JS error in the BG Log view.
The reason it wasn't was that we were using D3's `utcHour.range` method to generate the fill intervals, which messed up the `hourOfDay` calculations for these time zones.
Related PR: tidepool-org/blip#729
[WEB-805]: https://tidepool.atlassian.net/browse/WEB-805

[WEB-805] Fix BG Log crashes for patients viewing data in time zones with irregular offsets

---

package.json
src/modules/print/BasicsPrintView.js
src/modules/print/BgLogPrintView.js
src/modules/print/DailyPrintView.js
src/modules/print/PrintView.js
src/utils/basics/data.js
stories/print/BasicsViewPrintPDF.js
stories/print/BgLogViewPrintPDF.js
stories/print/CombinedViewPrintPDF.js
stories/print/DailyViewPrintPDF.js
stories/print/SettingsViewPrintPDF.js
test/modules/print/BasicsPrintView.test.js
test/modules/print/DailyPrintView.test.js
test/modules/print/PrintView.test.js
test/utils/basics/data.test.js

See [WEB-981] for details.
This involved updating the PDF logic to optimize chart placements in order to, for instance, prevent a basics calendar from rendering over page breaks.
Also, the storybooks are updated to leverage the PDF data queries from blip.
Related PR: tidepool-org/blip#829
[WEB-981]: https://tidepool.atlassian.net/browse/WEB-981

[WEB-981] Customizable print date ranges

---

data/print/fixtures.js
package.json
src/components/common/stat/Stat.css
src/components/common/stat/Stat.js
src/modules/print/BasicsPrintView.js
src/utils/AggregationUtil.js
src/utils/DataUtil.js
src/utils/StatUtil.js
src/utils/basics/data.js
stories/components/common/stats/Stat.js
test/components/common/stat/Stat.test.js
test/modules/print/BasicsPrintView.test.js
test/utils/basics/data.test.js

See [WEB-993]
Goes with:
tidepool-org/blip#843
tidepool-org/tideline#409
[WEB-993]: https://tidepool.atlassian.net/browse/WEB-993

[WEB-993] Add option to exclude days with no boluses from basics calendar aggregations and stats

---

data/types.js
package.json
src/components/common/stat/Stat.css
src/components/common/stat/Stat.js
src/modules/print/BasicsPrintView.js
src/modules/print/DailyPrintView.js
src/utils/StatUtil.js
src/utils/stat.js
stories/components/common/stats/Stat.js
test/components/common/stat/Stat.test.js
test/modules/print/DailyPrintView.test.js
test/utils/StatUtil.test.js
test/utils/stat.test.js

See [WEB-717]
Adds support for exchange units in:
1. the Settings view I:C ratio
2. the Daily view wizard tooltips
3. the carbs stat (shown on Basics and Daily via blip)
4. The print view (Basics, Daily, Settings)
Related PRs
---
https://github.com/tidepool-org/tideline/pull/419
https://github.com/tidepool-org/blip/pull/871
[WEB-717]: https://tidepool.atlassian.net/browse/WEB-717

[WEB-717] Support carb exchanges

---

package.json
src/components/daily/bolustooltip/BolusTooltip.js
src/utils/DataUtil.js
src/utils/StatUtil.js
src/utils/annotations.js
src/utils/settings/textData.js
src/utils/stat.js
test/components/daily/BolusTooltip.test.js
test/utils/DataUtil.test.js
test/utils/annotations.test.js

It was discovered during testing of [WEB-717] that uploads for the Medtronic 5 and 7 series carb exchange data was converting the exchanges to carbs (and then rounding to nearest integer) at a 1:15 ratio.  
This conversion was intended to be removed when `carbUnits` was added to the data model, but it was missed.  We've decided to de-convert it on the frontend for the time being.  As well, the `insulinCarbRatio` on wizard datums needs de-conversion as well.  In that case, due to rounding and the very granular precision that might be used to input the ratios on the pump, there is potential irrecoverable precision loss.  For this, we add an annotation to the bolus tooltip for any carb ratios that could be affected.  The carb ratio on the settings view is fully precise.
There is a backend …

[WEB-717] De-convert carb exchanges for Medtronic 5- and 7-series pumps

---

data/types.js
package.json
src/utils/DataUtil.js
src/utils/basics/data.js
test/utils/DataUtil.test.js

Part of [WEB-775].
This PR is to exclude pre-control-iq tandem uploads by default if we have data from the same device from a version of uploader supports control-iq data. 
Otherwise, we have duplicate data - specifically because the 'shape' of the bolus and basal datums changed due to the 'automated' subTypes, which in turn cause the generated datum id's to differ, and jellyfish deduplication does not happen.
To distinguish between data from uploads from a control-iq-capable pump prior to the adding of the automated subTypes, on the latest uploader version, we add begin the deviceId with `tandemCIQ` instead of just `tandem`, and, if we have, for instance, a `tandemCIQ123456789` device, we filter out, if present, by default,  the `tandem123456789` device.
[WEB-775]: …

[WEB-775] Filter out non-control-iq upload data if control-iq data is present

---

package.json
src/components/trends/common/TrendsContainer.js

Part of [WEB-1157]
Fixes issue where forward and 'most recent' date range calculations weren't accounting for DST changeovers.
Related PR: https://github.com/tidepool-org/blip/pull/890
[WEB-1157]: https://tidepool.atlassian.net/browse/WEB-1157

[WEB-1157] Trends navigation fixes

---

package.json
src/utils/DataUtil.js
stories/data/DataUtil.js
storybook/config.js

This is to allow us to use a variety of download sources in the DataUtil storybook, rather than just the private `accountTool.py` exports.
Main driving factor is a clinic IT team that would like to play with it.
Related PR: https://github.com/tidepool-org/blip/pull/971

Allow DataUtil storybook to use raw data from the API or blip console downloads

---

package.json
src/modules/print/BasicsPrintView.js
src/utils/stat.js
stories/components/common/stats/Stat.js
test/modules/print/BasicsPrintView.test.js
test/utils/stat.test.js

As the functionality was tightly related, this PR covers [WEB-1369], [WEB-1370], and [WEB-1371]
Related PR: https://github.com/tidepool-org/blip/pull/995
[WEB-1369]: https://tidepool.atlassian.net/browse/WEB-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1370]: https://tidepool.atlassian.net/browse/WEB-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1371]: https://tidepool.atlassian.net/browse/WEB-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1369,WEB-1370,WEB-1371] Updates to PDF and Text Stat output

---

package.json
src/components/common/stat/Stat.js
test/components/common/stat/Stat.test.js

See [WEB-1412]
Edge case where the method of disabling bar stats when the sum of the bars is < 0.  NaN values are converted to -1, so in some cases where there are small positive values, the sum could still be below zero.  
Negative values are now dropped before summing values to determine the disabled state.
Related PR: https://github.com/tidepool-org/blip/pull/1021
[WEB-1412]: https://tidepool.atlassian.net/browse/WEB-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1412] Fix incorrect disabled state criteria on stats

---

package.json
src/components/common/controls/ClipboardButton.js
src/index.js

Exports the `generateBgRangeLabels` util to support https://github.com/tidepool-org/blip/pull/1054

[WEB-1338] Export bg range label util

---

package.json
src/utils/bloodglucose.js
test/utils/bloodglucose.test.js

to support [WEB-1695], adds a new `segmented` option for generating range labels
paired with https://github.com/tidepool-org/blip/pull/1087
[WEB-1695]: https://tidepool.atlassian.net/browse/WEB-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1695] TIR filter update

---

package.json
src/utils/AggregationUtil.js
test/utils/AggregationUtil.test.js

[WEB-1593]
Basically, the aggregation utility doesn't create a date key for each date in the given range -- only those with data of some sort.  This would cause the stat aggregations in the daily print views to show summaries for the wrong day in the event that there were days missing data.
[WEB-1593]: https://tidepool.atlassian.net/browse/WEB-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1593] Fix issue where aggregations by date were being stored under the incorrect date key

---

package.json
src/utils/basics/data.js
test/utils/basics/data.test.js

[WEB-2055]
The function that checks for the existence of data for a given Basics section now prioritizes checking the `summary.total` value, when available, which is more dependable than counting the aggregated data by date keys, which can be present, but have no data within them.
Related PR: https://github.com/tidepool-org/blip/pull/1267
[WEB-2055]: https://tidepool.atlassian.net/browse/WEB-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2055] Fix for checking whether or not a basics section has data or not

---

package.json
src/utils/AggregationUtil.js
src/utils/DataUtil.js
src/utils/basics/data.js
src/utils/bgLog/data.js
src/utils/trends/data.js
test/utils/DataUtil.test.js
test/utils/trends/data.test.js

[WEB-2503], [WEB-2504], [WEB-2506] 
Related PR: https://github.com/tidepool-org/blip/pull/1272
The previous method of determining matched devices as datums were normalized was insufficient.
It left many edge cases, especially for stat and aggregations, where it would work in some cases where data happened to be normalized as part of the stat generation process, but it wasn't guaranteed.
This now uses a crossfilter change handler that will generate the matched devices whenever the `byType` filter is changed to any datum types we visualize.  I'm using a `matchDevices` property on the DataUtil to control when this behavior occurs since we only want to do this while generating data for the `current` range period, and not the `prev` and `next` ones that get generated for some of the data …

[WEB-2503,WEB-2504,WEB-2506] Fix bugs in matched device generation

---

package.json
src/modules/print/BasicsPrintView.js
src/utils/stat.js
test/modules/print/BasicsPrintView.test.js

[WEB-2620]
Missed updating the data path for counts in the readings in range stat annotations.  Also fixes a small text-wrapping issue on the basics summary tables that I noticed.
Related PR: https://github.com/tidepool-org/blip/pull/1305
[WEB-2620]: https://tidepool.atlassian.net/browse/WEB-2620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2620] Fix bgm count for basics readings in range stat

---

package.json
src/utils/DataUtil.js
test/utils/DataUtil.test.js

[WEB-3251] Will go out as part of `1.81.1` hotfix
Moved the general logic for determining the ideal timezone based on data from blip to the data worker here, as well as including the latest `dosingDecision` datums, and `timeChange` device events to address Loop and Apple Health datasets falling back to browser timezone.
The data util seems to me like a better place to do this, and we would have had to send additional data out to blip anyhow in order to utlilze the latest time change data as a potential fallback for Apple Health-only datasets. 
Also added some missing unit tests for `DataUtil.setLatestDiabetesDatumEnd` that missed adding during `1.81.0` development.
[WEB-3251]: https://tidepool.atlassian.net/browse/WEB-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

[WEB-3251] Set latestTimeZone metadata in data worker upon ingestion

---

package.json
src/components/common/stat/BgBar.js
src/components/common/stat/BgBarLabel.js
src/components/common/stat/HoverBar.js
src/components/common/stat/HoverBarLabel.js
src/components/common/stat/Stat.js
storybook/main.js
test/components/common/stat/BgBar.test.js
test/components/common/stat/HoverBar.test.js
test/components/common/stat/Stat.test.js
yarn.lock

The last of the first round of deep dependency updates. Much more detail in the ticket for [WEB-3179], but had to navigate through multiple layers of breaking major version updates in `victory-charts` in order to get to a `d3` subdependency version that no longer had a security issue associated with it. While I was heading to the fridge anyway, I moved `victory-charts` to the latest version instead of one major version behind latest.
paired with blip pr: https://github.com/tidepool-org/blip/pull/1499
[WEB-3179]: https://tidepool.atlassian.net/browse/WEB-3179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3179] dep updates

---

package.json
src/utils/DataUtil.js
src/utils/basics/data.js

[WEB-3030]
Also contains a small fix for the extended bolus filter being unintentionally removed for twiist loop
Related PR: https://github.com/tidepool-org/blip/pull/1542
[WEB-3030]: https://tidepool.atlassian.net/browse/WEB-3030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3030] Fix Twiist Loop override durations

---

package.json
src/utils/bloodglucose.js
test/utils/bloodglucose.test.js

[WEB-3396]
Use cgm sampleInterval property when available for determining the sample frequency to use in stats.
Related PR: https://github.com/tidepool-org/blip/pull/1544
[WEB-3396]: https://tidepool.atlassian.net/browse/WEB-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3396] Use cgm sampleInterval property when available

---

package.json
src/utils/basal.js
test/utils/basal.test.js

[WEB-3526] Time in auto duration fix.  This PR fixes a scope item that was missed in the last PR, which only fixed the Basal/Bolus ratio stats when a basal datum encompasses an entire endpoint range.
In this case, I had to adjust the unit tests for the new code to pass, but this was due to bad test data fixtures - the durations in the test data did not match the start and end times of the datums (duration was off by 12 hours on the affected datums)
I have confirmed that the functionality is now working as expected, and it was the tests that were wrong.
Related PR: https://github.com/tidepool-org/blip/pull/1554
[WEB-3526]: https://tidepool.atlassian.net/browse/WEB-3526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3526] Time in auto duration fix

---

src/components/common/stat/Stat.js

[WEB-3537]
The issue is that tapping and holding a VictoryChart with your thumb doesn't scroll the page. 
Looks like we're not the only ones who ran into this issue: https://github.com/FormidableLabs/victory/issues/1037#issuecomment-623048143
[WEB-3537]: https://tidepool.atlassian.net/browse/WEB-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Resolved:
https://github.com/user-attachments/assets/d7eed1da-accc-4757-a28d-901bedc96619

WEB-3537 - Fix scrolling issue

---

package.json
src/utils/bloodglucose.js

[WEB-3547] 
Basically, just needed an existential check on that the datum is defined when checking sample frequency.  
Related PR: https://github.com/tidepool-org/blip/pull/1557
[WEB-3547]: https://tidepool.atlassian.net/browse/WEB-3547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3547] Sample interval error fix for AGP prints

---

data/types.js
package.json
src/components/daily/bolustooltip/BolusTooltip.js
src/utils/DataUtil.js
src/utils/bolus.js
test/components/daily/BolusTooltip.test.js
test/utils/DataUtil.test.js
test/utils/bolus.test.js

[WEB-3687] 
Properly handles extended twiist dosing decision data, mapping to expected fields on boluses for visualization.  Also, maps dosing decisions to bolus by definitive id associations when provided, as twiist currently does, and Loop is expected to do in the future.  Falls back to the proximate method we've been doing, with a couple of failsafes added to make sure we never end up proximally mapping a dosing decision to more than one bolus.  
Also includes a fix to ensure that a requested bolus normal is only mapped to `bolus.expectedNormal` it does not match `bolus.normal`
[WEB-3697]
Updates to one-button bolus checks to properly apply label to bolus tooltip for dosing decisions.
[WEB-3698] 
Reverted the `recommendedBolus.normal` back to `recommendedBolus.amount` in light of new …

[WEB-3687|WEB-3697|WEB-3698] Handle twiist dosing decision extended bolus props + small tweaks for normal and oneButton

---

test/components/settings/Tandem.test.js
test/modules/print/SettingsPrintView.test.js

When I merged in some copy changes for Tandem annotations in https://github.com/tidepool-org/viz/pull/480 for [WEB-3717], I missed that there were a couple of tests broken.  This PR fixes those tests so that `develop` is in a passing state.
[WEB-3717]: https://tidepool.atlassian.net/browse/WEB-3717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3717] Fix broken tests

---

package.json
src/components/daily/bolustooltip/BolusTooltip.js
src/utils/DataUtil.js
test/components/daily/BolusTooltip.test.js
test/utils/DataUtil.test.js

[WEB-3777] 
We were already setting the bgHistorical last entry to `bolus.bgInput` within the dataUtil.  We just weren't using that in the bolus tooltip for dosing decisions.
With this PR, we will use the value in `bolus.bgInput`.  I also moved the code giving precedence to `dosingDecision.smbg.value` out of the bolus tooltip component and into the dataUtil, mapping that to `bolus.bgInput` if it's available.
Related PR: https://github.com/tidepool-org/blip/pull/1657
[WEB-3777]: https://tidepool.atlassian.net/browse/WEB-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3777] Use bgHistorical instead of bgForecast for bg input display on bolus tooltips for dosing decisions

---

src/utils/DataUtil.js
src/utils/bolus.js
test/utils/DataUtil.test.js
test/utils/bolus.test.js

For [WEB-3796], allows for handling the case that bolus.extended is 0. Additionally updates some optional chaining uses that are coerced to booleans but can have valid 0 values.
[WEB-3796]: https://tidepool.atlassian.net/browse/WEB-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3796] extended 0 handling

---

package.json
src/modules/print/BasicsPrintView.js
src/modules/print/SettingsPrintView.js
src/utils/settings/data.js
test/modules/print/SettingsPrintView.test.js
test/utils/settings/data.test.js

[WEB-3836] 
Also includes a few minor tweaks to gutter widths and column spacing to optimize being able to show values and labels without spilling over to new lines on the settings print view.
The 1px gutter witdh update was also applied to the basics view for consistency.
Related PR: https://github.com/tidepool-org/blip/pull/1685
[WEB-3836]: https://tidepool.atlassian.net/browse/WEB-3836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3836] Max basal precision update
