tidepool-org/viz

.travis.yml
=> add a before_install to get the right version of npm

README.md
=> improve running locally instructions

.eslintrc, package.json, src/utils/.eslintrc
Strawman proposal for additions to our ESLint config.
Added the plugin for lodash to prefer *all* lodash methods over native. (This will be a lot of changes. We can be more nuanced if we want. Let's discuss.)
Also added an additional config in utils/ to add the rule (only in that dir) to require JSDoc comments.
CC @krystophv @jh-bate Please try it out with an experimental merge into your working branch and let's discuss.
=> ESLint additions

README.md
Merge if you don't have questions/comments/additions @jh-bate 
Ping @krystophv to take a look, need to get your npm account (or you need to create one) so we can add you to the org.
=> add instructions for publishing to npm

src/components/settings/animas/Animas.css, src/components/settings/animas/Animas.js, src/components/settings/medtronic/Medtronic.css, src/components/settings/medtronic/Medtronic.js, src/components/settings/omnipod/Omnipod.css, src/components/settings/omnipod/Omnipod.js, src/components/settings/settings.css, src/utils/datetime.js, src/utils/settings/data.js, test/utils/datetime.test.js, test/utils/settings/data.test.js
@krystophv fixes related to Brandon's notes on the card for testing. Couldn't get the columns correct for the medtronic settings but I am sure its a 5 min fix for you :)
See https://trello.com/c/0ynkcbTR for notes but with this tweak the basal total match's what is on prod for Medtronic and I think that they have a rounding issue based on the details we get.
Thanks
Jamie
=> updates based on settings testing for medtronic

src/components/settings/common/Table.css, src/components/settings/common/Table.js
=> separate out styles for secondary labels w/ and w/o main text

package.json, src/components/trends/common/YAxisLabelsAndTicks.js, test/components/trends/common/YAxisLabelsAndTicks.test.js
to complement the adjustments for custom target ranges in tideline
=> adding veryLowThreshold tick/label

package.json, src/components/settings/NonTandem.js, stories/components/settings/DeviceSettings.js, stories/helpers/SixHrScaleSVGDecorator.js, storybook/addons.js
Nothing major here; everything restricted to Storybook code except for the minor cleanup re: settings propTypes . @jh-bate if you think this is fine, let's merge to master so I can include it in my other branch for daily print view. I'm happy to do the merge update on your device settings c&p branch to resolve the conflicts if you want.
=> Storybook updates

.travis.yml, package.json
=> update Travis config & npm engines for node v6.x

.bookignore, .gitignore, .npmignore, yarn.lock
What it says on the tin. Some straggler changes resulting from when I went to publish the docs after merging #58.
=> update ignore files to exclude local/, .sketch files where appropriate, yarn.lock where appropriate

package.json, src/components/settings/Tandem.js, test/components/settings/NonTandem.test.js, test/components/settings/Tandem.test.js
@jebeck added some tests for button click ... doesn't solve the issue of `copySettingsClicked` vs `copySettingsClicked()` but it does test for the button click. Maybe you have another idea?
=> Copy settings metric tandem fix

SUMMARY.md, src/utils/apidocs/README.md, src/utils/apidocs/bloodglucose.md, src/utils/apidocs/bolus.md, src/utils/apidocs/datetime.md, src/utils/apidocs/format.md, src/utils/apidocs/misc.md
What it says on the tin. If you could verify it's only changes to Markdown files and approve @jh-bate, that'd be fantastic!
=> generate updated apidocs for utils & add missing ones to SUMMARY.md

data/bolus/fixtures.js, src/components/common/data/Bolus.css, src/components/common/data/Bolus.js, src/styles/colors.css, src/styles/diabetes.css, src/utils/basal.js, src/utils/bolus.js, src/utils/datetime.js, src/utils/format.js, test/components/common/data/Bolus.test.js, test/utils/basal.test.js, test/utils/bolus.test.js, test/utils/datetime.test.js, test/utils/format.test.js
Some pretty simple additions here. Branched off #77 just to keep my workflow simpler as the time crunch is getting more real...
=> additional utils for daily print view stats

src/utils/apidocs/basal.md, src/utils/apidocs/bloodglucose.md, src/utils/apidocs/bolus.md, src/utils/apidocs/datetime.md, src/utils/apidocs/format.md
Again what it says on the tin. Just needs someone to verify that it's only Markdown files that changed so can safely merge to master.
Already published to GitHub Pages along with the Storybooks.
=> regenerate utils .md file docs from JSDoc

package.json, src/modules/print/DailyPrintView.js, src/modules/render/basal.js, src/modules/render/bolus.js, src/utils/basal.js, src/utils/print/data.js, stories/print/DailyViewPrintPDF.js, test/modules/print/DailyPrintView.test.js, test/utils/basal.test.js
See https://trello.com/c/hLh5RXez
Goes hand-in-hand with same-named branch on `blip`
=> Fixes for print view basal rendering bugs

.dockerignore, Dockerfile, package.json
Goes hand-in-hand with the corresponding `clintb/development-build-fixes` branch in these repos:
https://github.com/tidepool-org/blip
https://github.com/tidepool-org/tools
See this trello card for any additional details:
https://trello.com/c/PnIamSBO
=> Improvements and fixes for the docker development experience

package.json, src/components/settings/NonTandem.js, src/index.js, src/modules/print/DailyPrintView.js, src/utils/bloodglucose.js, src/utils/constants.js, src/utils/settings/textData.js, stories/print/DailyViewPrintPDF.js, test/components/settings/NonTandem.test.js, test/helpers/bgConversion.js, test/modules/print/DailyPrintView.test.js, test/utils/constants.test.js
See https://trello.com/c/FJKBYCVt for complete details
Note: this PR goes hand-in-hand with the correspondingly-named branches and PR's on the `blip` and `tideline` repos:
https://github.com/tidepool-org/tideline/pull/318
https://github.com/tidepool-org/blip/pull/439
=> Add full support for mmol/L BG units

package.json
Forgot to create production tag before merging branch to master.  Need to do it in separate PR now.
=> Production tag for Libre fixes

.dockerignore, .travis.yml, Dockerfile
@jh-bate @pazaan @cbwebdevelopment
=> Automatic Docker build and push

src/components/settings/NonTandem.js, src/components/settings/Tandem.js, src/modules/print/DailyPrintView.js, src/modules/print/SettingsPrintView.js, src/utils/constants.js, src/utils/print/data.js, src/utils/settings/data.js, src/utils/settings/nonTandemData.js, test/utils/constants.test.js
See https://trello.com/c/h1QqftJ6 for details.
Related PRs:
tidepool-org/blip#475
tidepool-org/tideline#334
=> Basal auto/scheduled label mapping

loadtests.js, package.config.js, package.json, src/components/daily/bolustooltip/BolusTooltip.js, src/components/settings/NonTandem.js, src/components/settings/Tandem.js, src/components/settings/common/Header.js, src/components/trends/cbg/RangeSelect.js, src/components/trends/common/NoData.js, src/index.js, src/modules/print/DailyPrintView.js, src/modules/print/PrintView.js, src/modules/print/index.js, src/utils/basics/data.js, src/utils/settings/nonTandemData.js, src/utils/settings/textData.js, yarn.lock
This enables multi-language in viz. This PR is destined to be used in conjunction with https://github.com/tidepool-org/blip/pull/473.
=> Localization

data/pumpSettings/medtronic/automated.json, src/components/settings/NonTandem.css, src/components/settings/NonTandem.js, src/components/settings/common/PumpSettingsContainer.js, src/components/settings/settings.css, src/modules/print/DailyPrintView.js, src/modules/print/PrintView.js, src/modules/print/SettingsPrintView.js, src/utils/settings/nonTandemData.js, stories/print/SettingsViewPrintPDF.js, test/components/settings/NonTandem.test.js, test/components/settings/common/PumpSettingsContainer.test.js, test/modules/print/SettingsPrintView.test.js, test/utils/settings/nonTandemData.test.js
What it says.  See https://trello.com/c/Ni2DGNEI for details.
Goes with  tidepool-org/tideline#336
=> Show Auto Mode schedule on Settings view when is active at time of upload.

src/modules/print/BasicsPrintView.js, src/utils/basal.js, src/utils/basics/data.js, src/utils/classifiers.js, test/modules/print/BasicsPrintView.test.js, test/utils/basal.test.js, test/utils/basics/data.test.js, test/utils/classifiers.test.js
See https://trello.com/c/XwEYulG5 for details
Goes with tidepool-org/tideline#337
=> Basal Events in Basics view for 670G

data/print/fixtures.js, data/types.js, package.json, src/components/common/data/Basal.css, src/components/daily/bolustooltip/BolusTooltip.css, src/modules/print/BasicsPrintView.js, src/modules/print/DailyPrintView.js, src/styles/colors.css, src/utils/basal.js, src/utils/basics/data.js, src/utils/constants.js, src/utils/device.js, src/utils/print/data.js, src/utils/settings/data.js, test/components/common/data/Basal.test.js, test/modules/print/BasicsPrintView.test.js, test/modules/print/DailyPrintView.test.js, test/utils/basal.test.js, test/utils/basics/data.test.js, test/utils/constants.test.js, test/utils/device.test.js, test/utils/print/data.test.js, test/utils/settings/data.test.js
See https://trello.com/c/nvJocRRd for details.
This PR adds the widget to the print views.
Related PRs:
tidepool-org/blip#485
tidepool-org/tideline#342
=> Time in Auto Mode widget

data/basal/fixtures.js, package.json, src/components/common/data/Basal.css, src/modules/print/DailyPrintView.js, src/modules/render/basal.js, src/utils/basal.js, storiesDatatypes/components/common/data/Basal.js, test/modules/render/basal.test.js, test/utils/basal.test.js
See https://trello.com/c/UCwOXfD7 for details.
Related PRs:
tidepool-org/blip#489
tidepool-org/tideline#344
=> Automated basal suspend fix

package.json, src/components/daily/bolustooltip/BolusTooltip.js, stories/components/daily/BolusTooltip.js, test/components/daily/BolusTooltip.test.js
Adds affordance for handling auto mode target representation
Trello card: https://trello.com/c/krrF6CmW
blip PR: https://github.com/tidepool-org/blip/pull/496
=> Auto target

package.json, src/modules/print/DailyPrintView.js, test/modules/print/DailyPrintView.test.js
See https://trello.com/c/4vRWbVp3 for details.
Related PR:
tidepool-org/blip#500
=> Daily print view y-axis tick formatting regression

data/basal/fixtures.js, package.json, src/modules/render/basal.js, src/utils/basics/data.js, test/modules/render/basal.test.js, test/utils/basics/data.test.js
See https://trello.com/c/uzlypSjy for details.
Related PRs
---
tidepool-org/blip#503
tidepool-org/tideline#353
=> Basics page shows incorrect suspend count

package.json, src/components/trends/common/NoData.js, static/pdfkit.js, test/components/trends/common/NoData.test.js
See https://trello.com/c/Jdwx1isM for details.
Related PRs:
tidepool-org/blip#492
tidepool-org/tideline#346
=> Project Casper

package.json, src/utils/bloodglucose.js, test/utils/bloodglucose.test.js
See https://trello.com/c/VNKOkCOY for details.
Related PRs:
---
tidepool-org/blip#505
tidepool-org/tideline#354
=> Fix missing device id error

data/deviceEvent/fixtures.js, package.json, src/components/common/data/Suspend.js, storiesDatatypes/components/common/data/Suspend.js, test/components/common/data/Suspend.test.js
blip: https://github.com/tidepool-org/blip/pull/514
tideline: https://github.com/tidepool-org/tideline/pull/358
trello: https://trello.com/c/wZk0cMNU
=> Auto suspend markers

data/deviceEvent/fixtures.js, package.json, src/components/common/data/Suspend.js, storiesDatatypes/components/common/data/Suspend.js, test/components/common/data/Suspend.test.js
Release contains PLGS markers.
trello: https://trello.com/c/wZk0cMNU
Released in concert with:
blip: https://github.com/tidepool-org/blip/pull/516
tideline: https://github.com/tidepool-org/tideline/pull/359
Note: will receive final version post PR approval.
=> Release 0.12.0

data/print/fixtures.js, package.json, src/index.js, src/modules/print/BasicsPrintView.js, src/modules/print/DailyPrintView.js, src/modules/print/PrintView.js, src/modules/print/WeeklyPrintView.js, src/modules/print/index.js, src/styles/colors.css, src/utils/print/data.js, stories/print/BasicsViewPrintPDF.js, stories/print/CombinedViewPrintPDF.js, stories/print/DailyViewPrintPDF.js, stories/print/SettingsViewPrintPDF.js, stories/print/WeeklyViewPrintPDF.js, test/modules/print/BasicsPrintView.test.js, test/modules/print/DailyPrintView.test.js, test/modules/print/PrintView.test.js, test/modules/print/WeeklyPrintView.test.js, test/modules/print/index.test.js, yarn.lock
See https://trello.com/c/1H0rCVys for details.
Related PRs
---
tidepool-org/blip#518
=> Weekly print view

src/components/common/stat/Stat.css, src/components/common/stat/Stat.js, src/utils/stat.js, stories/components/common/stats/Stat.js, test/components/common/stat/Stat.test.js, test/utils/stat.test.js
See https://trello.com/c/8w4zfRPq for details.
Goes with tidepool-org/blip#542
=> Persist Average Daily Dose input between data views

package.json, src/utils/stat.js, test/utils/stat.test.js
Merge release branch back into `develop`
=> Release 1.1.0

package.json
Merge release 1.3.0 to develop
=> Release 1.3.0 to develop

.travis.yml, artifact.sh
This builds Docker images in Travis for each push that passes unit tests.
=> Build docker images in travis.

package.json, src/utils/constants.js, test/utils/constants.test.js
https://trello.com/c/KDHf69KK/663-time-in-auto-stat-not-showing-for-medtronic-670g-devices-with-devicemodel-1782#
=> add model 1782 to code and unit tests

package.json
Deployment details: https://trello.com/c/xOr2vLq3
=> Release 1.5.0 to develop

package.json
Resolves [WEB-165]
[WEB-165]: https://tidepool.atlassian.net/browse/WEB-165
=> Release 1.8.0 [WEB-165] to develop

stories/print/DailyViewPrintPDF.js
[WEB-257] updated print view to include 15 days
[WEB-257]: https://tidepool.atlassian.net/browse/WEB-257
=> updated print view to include 15 days (WEB-257)

src/utils/basics/data.js, test/utils/basics/data.test.js
Addresses rounding issue found while in QA for WEB-2
=> Round Mean Duration in basics text to 1 decimal place [WEB-2]

package.json, src/utils/basics/data.js, test/utils/basics/data.test.js
Part of [Release v1.29.0](https://tidepool.atlassian.net/projects/WEB/versions/10074/tab/release-report-all-issues)
=> Release 1.9.0 to develop

src/modules/print/DailyPrintView.js, test/modules/print/DailyPrintView.test.js
Hey @cbwebdevelopment -- left my notes in for now for your review -- will remove them after you've had a chance to check it out, feedback much appreciated
=> [WEB-198] targetUpperBound --> clampThreshold

package.json, src/utils/DataUtil.js, src/utils/validation/schema.js, test/utils/validation/schema.test.js, yarn.lock
Fixes [WEB-709]
[WEB-709]: https://tidepool.atlassian.net/browse/WEB-709
=> [WEB-709] CSP validation fix

package.json, src/utils/basics/data.js, test/utils/basics/data.test.js
See [WEB-750] for details.
Goes with tidepool-org/blip#670
[WEB-750]: https://tidepool.atlassian.net/browse/WEB-750
=> [WEB-750] Fix basics copy-to-text empty calibration values

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
Addresses [WEB-770]
Part of tidepool-org/blip#682
[WEB-770]: https://tidepool.atlassian.net/browse/WEB-770
=> [WEB-770] Ensure latest pump settings removed from data worker when patient id changes

package.json, src/utils/DataUtil.js, src/utils/validation/schema.js, test/utils/validation/schema.test.js
See [WEB-787] for details
Related PR: tidepool-org/blip#698
[WEB-787]: https://tidepool.atlassian.net/browse/WEB-787
=> [WEB-787] Hotfix: extended bolus validation fix

package.json, src/utils/DataUtil.js, src/utils/validation/schema.js, test/utils/validation/schema.test.js
Closes [WEB-787] hotfix release
[WEB-787]: https://tidepool.atlassian.net/browse/WEB-787
=> Merge [WEB-787] extended bolus validation fix to develop

package.json, src/modules/print/BasicsPrintView.js
See [WEB-791] for details.
Related PR: tidepool-org/blip#704
[WEB-791]: https://tidepool.atlassian.net/browse/WEB-791
=> [WEB-791] Add GMI to basics view PDF

package.json, src/modules/print/BasicsPrintView.js
[WEB-791]
[WEB-791]: https://tidepool.atlassian.net/browse/WEB-791
=> Release 1.11.4 [WEB-791]

package.json
Merge release branch for [WEB-805] back to `develop`
[WEB-805]: https://tidepool.atlassian.net/browse/WEB-805
=> Release 1.11.5 to develop [WEB-805]

package.json, src/components/common/stat/Stat.js, test/components/common/stat/Stat.test.js
See [WEB-1003] for details
Related PR: tidepool-org/blip#790
[WEB-1003]: https://tidepool.atlassian.net/browse/WEB-1003
=> [WEB-1003] Stat animation precision fix

package.json, src/utils/StatUtil.js, src/utils/stat.js, stories/data/DataUtil.js, test/utils/StatUtil.test.js, test/utils/stat.test.js
Jira Ticket: https://tidepool.atlassian.net/browse/WEB-889
=> [WEB-889] Add low/high bg values to stats

package.json, src/utils/AggregationUtil.js, src/utils/DataUtil.js, stories/data/DataUtil.js, test/utils/DataUtil.test.js
Adds deviceIds dimension and filter for data utils for [WEB-162].
Commits cherry picked from https://github.com/tidepool-org/viz/pull/227 and replayed against `master` 
blip: https://github.com/tidepool-org/blip/pull/808
tideline: https://github.com/tidepool-org/tideline/pull/405
[WEB-162]: https://tidepool.atlassian.net/browse/WEB-162
=> [WEB-162] device filter to 'master'

.gitignore, package.json, yarn.lock
Supporting PR for tidepool-org/blip#831
=> Add @hot-loader/react-dom to facilitate using npm-link-up

data/print/fixtures.js, package.json, src/modules/print/BasicsPrintView.js, test/modules/print/BasicsPrintView.test.js
See [WEB-980]
Related PR: tidepool-org/blip#845
[WEB-980]: https://tidepool.atlassian.net/browse/WEB-980
=> [WEB-980] Add CV stat to basics print view

package.json
Merges work for [v1.40.0](https://tidepool.atlassian.net/projects/WEB/versions/10160/) to develop
=> Release 1.16.0 to develop

package.json, src/components/daily/foodtooltip/FoodTooltip.js, test/components/daily/FoodTooltip.test.js
Part of [WEB-606]
Related PRs
---
tidepool-org/blip#861
tidepool-org/tideline#417
[WEB-606]: https://tidepool.atlassian.net/browse/WEB-606
=> [WEB-606] Carb rounding for food datums in daily view timeline tootips

data/print/fixtures.js, package.json, src/modules/print/DailyPrintView.js, test/modules/print/DailyPrintView.test.js
See [WEB-1127]
Related PR: tidepool-org/blip#865
[WEB-1127]: https://tidepool.atlassian.net/browse/WEB-1127
=> [WEB-1127] Round carbs from HealthKit in print view

package.json
See [WEB-1127]
[WEB-1127]: https://tidepool.atlassian.net/browse/WEB-1127
=> Release 1.18.0 to develop [WEB-1127]

package.json, src/utils/bolus.js, test/utils/bolus.test.js
See [WEB-1137]
Related PR:
https://github.com/tidepool-org/blip/pull/873
[WEB-1137]: https://tidepool.atlassian.net/browse/WEB-1137
=> [WEB-1137] Fix PDF bolus rendering errors 

package.json, src/utils/validation/schema.js, test/utils/validation/schema.test.js
See [WEB-775] for more details.
Goes with:
- https://github.com/tidepool-org/tideline/pull/412
[WEB-775]: https://tidepool.atlassian.net/browse/WEB-775
=> Add validation for automated boluses (WEB-775)

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js, test/utils/StatUtil.test.js
Hotfix. See [WEB-1151].
Related PR: https://github.com/tidepool-org/blip/pull/882
[WEB-1151]: https://tidepool.atlassian.net/browse/WEB-1151
=> [WEB-1151] Reject duplicate wizards

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js, test/utils/StatUtil.test.js
Merge hotfix [WEB-1151] back to release branch
[WEB-1151]: https://tidepool.atlassian.net/browse/WEB-1151
=> [WEB-1151] merge to release-1.20.0

package.json, src/utils/device.js, test/utils/DataUtil.test.js, test/utils/device.test.js
See [WEB-1171] for details.
[WEB-1171]: https://tidepool.atlassian.net/browse/WEB-1171
=> [WEB-1171] Hotfix: Fix CIQ capabilities checks

package.json, src/utils/device.js, test/utils/DataUtil.test.js, test/utils/device.test.js
Merges hotfix [WEB-1171] to develop
[WEB-1171]: https://tidepool.atlassian.net/browse/WEB-1171
=> [WEB-1171] Merge hotfix to develop

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
See [WEB-1179]
Related PR: https://github.com/tidepool-org/blip/pull/905
[WEB-1179]: https://tidepool.atlassian.net/browse/WEB-1179
=> [WEB-1179] Fix for incorrect devices count when switching users

package.json, src/modules/print/BasicsPrintView.js, test/modules/print/BasicsPrintView.test.js
See [WEB-1201]
Related PR: https://github.com/tidepool-org/blip/pull/945
[WEB-1201]: https://tidepool.atlassian.net/browse/WEB-1201
=> [WEB-1201] Add Avg. Glucose to Basics portion of PDF printout

package.json
Merge release 1.22.0 back to develop
=> Release 1.22.0 to develop

package.json, src/components/common/stat/Stat.css, src/components/common/stat/Stat.js, src/components/settings/common/CollapsibleContainer.css, src/components/settings/common/CollapsibleContainer.js, src/modules/print/BasicsPrintView.js, src/utils/basics/data.js, src/utils/stat.js, stories/components/common/stats/Stat.js
Part of [WEB-1204]
Most of the work was already completed in the original Stat implementation, but there was some styling/formatting work remaining to do.
Related PR: https://github.com/tidepool-org/blip/pull/984
[WEB-1204]: https://tidepool.atlassian.net/browse/WEB-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1204] Finish collapsible stats implementation

data/pumpSettings/medtronic/automated.json, data/pumpSettings/medtronic/flatrate.json, data/pumpSettings/medtronic/multirate.json, data/pumpSettings/omnipod/flatrate.json, data/pumpSettings/omnipod/multirate.json, data/pumpSettings/tandem/flatrate.json, data/pumpSettings/tandem/multirate.json, package.json, src/components/settings/NonTandem.css, src/components/settings/NonTandem.js, src/components/settings/Tandem.css, src/components/settings/Tandem.js, src/components/settings/common/Table.js, src/components/settings/settings.css, src/modules/print/PrintView.js, src/modules/print/SettingsPrintView.js, src/utils/constants.js, src/utils/device.js, src/utils/settings/data.js, src/utils/settings/tandemData.js, src/utils/settings/textData.js, src/utils/text/TextUtil.js, stories/print/SettingsViewPrintPDF.js, test/components/settings/NonTandem.test.js, test/components/settings/Tandem.test.js, test/modules/print/SettingsPrintView.test.js, test/utils/constants.test.js, test/utils/device.test.js, test/utils/settings/data.test.js
See [WEB-1188]
Related PR: https://github.com/tidepool-org/blip/pull/994
[WEB-1188]: https://tidepool.atlassian.net/browse/WEB-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1188] Add new device settings to web, print and text output

src/index.js, src/utils/DataUtil.js, src/utils/bloodglucose.js, test/utils/DataUtil.test.js, test/utils/bloodglucose.test.js
See [WEB-1213]
Related PR: https://github.com/tidepool-org/blip/pull/1002
[WEB-1213]: https://tidepool.atlassian.net/browse/WEB-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1213] Allow changing to default BG target ranges

package.json
Missed a version bump commit in the previous pull request.  Adding it here.
=> [WEB-1213] Add missing version bump commit

data/print/fixtures.js, data/types.js, package.json, src/modules/print/BasicsPrintView.js, src/utils/AggregationUtil.js, src/utils/DataUtil.js, src/utils/basics/data.js, src/utils/constants.js, stories/data/DataUtil.js, test/modules/print/BasicsPrintView.test.js, test/utils/AggregationUtil.test.js, test/utils/DataUtil.test.js, test/utils/basics/data.test.js, test/utils/constants.test.js, test/utils/device.test.js
Part of [WEB-49]
Related PRs:
https://github.com/tidepool-org/tideline/pull/429
https://github.com/tidepool-org/blip/pull/1014
[WEB-49]: https://tidepool.atlassian.net/browse/WEB-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-49] Basics Basal-IQ auto suspends

data/pumpSettings/omnipod/flatrate.json, data/pumpSettings/omnipod/multirate.json, data/pumpSettings/tandem/flatrate.json, package.json, src/components/settings/Tandem.js, src/utils/settings/data.js, test/components/settings/NonTandem.test.js, test/components/settings/Tandem.test.js, test/modules/print/SettingsPrintView.test.js, test/utils/settings/data.test.js
See [WEB-1465]
Related PR: https://github.com/tidepool-org/blip/pull/1030
[WEB-1465]: https://tidepool.atlassian.net/browse/WEB-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1465] Always display insulin duration settings in hours

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
See [WEB-1078]
Related PR https://github.com/tidepool-org/blip/pull/1037
[WEB-1078]: https://tidepool.atlassian.net/browse/WEB-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1078] Add queryDataCount metadata to data worker

package.json
=> Release 1.27.0 to develop

package.json
=> Release 1.29.0 to develop

package.json
Release is comprised exclusively of dependency updates
=> Release 1.30.0

data/types.js, package.json, src/components/common/controls/TwoOptionToggle.css, src/index.js, src/utils/bgLog/data.js, stories/components/common/controls/ClipboardButton.js, test/utils/bgLog/data.test.js, yarn.lock
=> Release v1.31.0 to master

package.json
=> Release v1.31.0 to develop

package.json, src/utils/text/TextUtil.js, test/utils/text/TextUtil.test.js
See [WEB-1877] 
Related PR: https://github.com/tidepool-org/blip/pull/1145
[WEB-1877]: https://tidepool.atlassian.net/browse/WEB-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1877] Add MRN to text output on data views

package.json
=> Release v1.32.0 to develop

package.json, src/utils/bloodglucose.js, stories/components/common/stats/Stat.js, test/utils/bloodglucose.test.js
[Web 2185]
Related PR: https://github.com/tidepool-org/blip/pull/1210
=> [Web 2185] Hotfix: use 5 minute cgm sample frequency for Libre 3 data

package.json
=> Update incorrect version for v1.33.1 release

package.json, src/modules/print/DailyPrintView.js, test/modules/print/DailyPrintView.test.js
[WEB-2252]
Related PR: https://github.com/tidepool-org/blip/pull/1214
[WEB-2252]: https://tidepool.atlassian.net/browse/WEB-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2252] Hotfix: time in target daily print view missing

package.json, src/modules/print/DailyPrintView.js, test/modules/print/DailyPrintView.test.js
=> Release 1.33.2 to develop

data/patient/profiles.js, package.json, src/modules/print/AGPPrintView.js, src/modules/print/PrintView.js, src/modules/print/utils/AGPConstants.js, stories/print/CombinedViewPrintPDF.js, test/helpers/pdfDoc.js, test/modules/print/AGPPrintView.test.js, test/modules/print/PrintView.test.js, test/modules/print/utils/AGPConstants.test.js
[WEB-2101] 
Related PR: https://github.com/tidepool-org/blip/pull/1233
[WEB-2101]: https://tidepool.atlassian.net/browse/WEB-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2101] Add MRN to pdf headers

package.json, src/modules/print/AGPPrintView.js, src/modules/print/PrintView.js, test/modules/print/AGPPrintView.test.js, test/modules/print/PrintView.test.js
Fixes [WEB-2451]
Related PR: https://github.com/tidepool-org/blip/pull/1256
[WEB-2451]: https://tidepool.atlassian.net/browse/WEB-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2451] MRN truncate fix

package.json, src/modules/print/AGPPrintView.js, src/modules/print/PrintView.js, test/modules/print/AGPPrintView.test.js, test/modules/print/PrintView.test.js
=> Release v1.34.0 to develop

package.json, src/index.js
[WEB-2348]
Supports https://github.com/tidepool-org/blip/pull/1263
[WEB-2348]: https://tidepool.atlassian.net/browse/WEB-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2348] Export formatDateRange utility

package.json, src/utils/DataUtil.js, src/utils/basics/data.js, src/utils/bgLog/data.js, src/utils/trends/data.js, stories/data/DataUtil.js, test/utils/DataUtil.test.js, test/utils/basics/data.test.js, test/utils/bgLog/data.test.js, test/utils/trends/data.test.js
[WEB-2246]
Related PR: https://github.com/tidepool-org/blip/pull/1269
[WEB-2246]: https://tidepool.atlassian.net/browse/WEB-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2246] Add uploaded devices to text output

package.json, src/utils/AggregationUtil.js, src/utils/DataUtil.js, src/utils/basics/data.js, src/utils/bgLog/data.js, src/utils/trends/data.js, test/utils/DataUtil.test.js, test/utils/trends/data.test.js
=> Release 1.35.0 to develop

package.json, src/index.js, src/utils/datetime.js
[WEB-2546] 
Supports https://github.com/tidepool-org/blip/pull/1284
[WEB-2546]: https://tidepool.atlassian.net/browse/WEB-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2546] Export "getOffset" datetime util

data/print/fixtures.js, package.json, src/modules/print/AGPPrintView.js, src/modules/print/index.js, src/modules/print/utils/AGPConstants.js, src/modules/print/utils/AGPUtils.js, src/utils/StatUtil.js, src/utils/bloodglucose.js, src/utils/print/plotly.js, src/utils/stat.js, stories/print/AGPViewPrintPDF.js, test/components/trends/smbg/SMBGRangeAvgContainer.test.js, test/modules/print/AGPPrintView.test.js, test/modules/print/index.test.js, test/modules/print/utils/AGPConstants.test.js, test/modules/print/utils/AGPUtils.test.js, test/utils/StatUtil.test.js, test/utils/bloodglucose.test.js, test/utils/print/plotly.test.js, test/utils/stat.test.js
[WEB-2387]
Related: https://github.com/tidepool-org/blip/pull/1286
[WEB-2387]: https://tidepool.atlassian.net/browse/WEB-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2387] Add bgm AGP print report

package.json, src/modules/print/DailyPrintView.js
[WEB-2618]
Related: https://github.com/tidepool-org/blip/pull/1304
[WEB-2618]: https://tidepool.atlassian.net/browse/WEB-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2618] Fix error generating daily print view for bgm data

package.json, src/modules/print/BasicsPrintView.js, src/modules/print/PrintView.js, src/modules/print/index.js, stories/print/CombinedViewPrintPDF.js
[WEB-2401]
Related PR: https://github.com/tidepool-org/blip/pull/1307
[WEB-2401]: https://tidepool.atlassian.net/browse/WEB-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2401] Move AGP to beginning of PDF reports

.gitignore, package.json, src/modules/print/BasicsPrintView.js, src/modules/print/DailyPrintView.js, src/modules/print/PrintView.js, src/modules/print/index.js, src/utils/stat.js, stories/print/CombinedViewPrintPDF.js, test/modules/print/BasicsPrintView.test.js
=> Release 1.37.0 to develop

package.json
=> Release 1.38.0 to develop

.travis.yml
Fix travis builds by removing buildx install step
=> Fix travis builds by removing buildx install step

package.json, src/utils/bloodglucose.js, src/utils/constants.js, test/utils/AggregationUtil.test.js, test/utils/StatUtil.test.js, test/utils/bloodglucose.test.js, test/utils/constants.test.js, test/utils/stat.test.js
[WEB-2992] 
Related PR: https://github.com/tidepool-org/blip/pull/1395
[WEB-2992]: https://tidepool.atlassian.net/browse/WEB-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2992] Add extreme hyper BG threshold

package.json
=> Release 1.40.0 to develop

package.json, src/index.js, src/utils/datetime.js, test/utils/datetime.test.js
[WEB-2994] [WEB-2993]
Related PRs:
---
https://github.com/tidepool-org/blip/pull/1396
https://github.com/tidepool-org/platform-client/pull/173
[WEB-2994]: https://tidepool.atlassian.net/browse/WEB-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2993]: https://tidepool.atlassian.net/browse/WEB-2993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2994,WEB-2993] Set patient's last reviewed on TIDE and Pop Health dashboards

package.json
=> Release 1.41.0 to develop

package.json, src/components/settings/common/Header.css, src/components/settings/common/Header.js, src/index.js, test/components/settings/common/Header.test.js
to address [WEB-3034] and [WEB-3035] adds selection options for devices and daily settings
paired with: https://github.com/tidepool-org/blip/pull/1421
[WEB-3034]: https://tidepool.atlassian.net/browse/WEB-3034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3035]: https://tidepool.atlassian.net/browse/WEB-3035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3034][WEB-3035] settings selection

data/pumpSettings/loop/multirate.json, package.json, src/components/common/tooltips/StatTooltip.css, src/components/common/tooltips/StatTooltip.js, src/components/common/tooltips/Tooltip.css, src/components/settings/NonTandem.css, src/components/settings/NonTandem.js, src/components/settings/common/Table.css, src/components/settings/common/Table.js, src/components/settings/settings.css, src/styles/colors.css, src/utils/device.js, src/utils/settings/data.js, src/utils/settings/nonTandemData.js, src/utils/settings/textData.js, stories/components/settings/DeviceSettings.js, test/utils/device.test.js, test/utils/settings/data.test.js
[WEB-3033] [WEB-3163]
Related PR: https://github.com/tidepool-org/blip/pull/1438
[WEB-3033]: https://tidepool.atlassian.net/browse/WEB-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3163]: https://tidepool.atlassian.net/browse/WEB-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3033,WEB-3163] Loop-specific therapy settings in device settings

package.json, src/components/daily/foodtooltip/FoodTooltip.js, src/modules/print/BasicsPrintView.js, src/utils/AggregationUtil.js, src/utils/DataUtil.js, src/utils/StatUtil.js, src/utils/constants.js, test/components/daily/FoodTooltip.test.js, test/modules/print/BasicsPrintView.test.js, test/utils/AggregationUtil.test.js, test/utils/StatUtil.test.js
[WEB-3115] [WEB-3116] [WEB-3128]
Related PR: https://github.com/tidepool-org/blip/pull/1439
[WEB-3115]: https://tidepool.atlassian.net/browse/WEB-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3116]: https://tidepool.atlassian.net/browse/WEB-3116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3128]: https://tidepool.atlassian.net/browse/WEB-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3115,WEB-3116,WEB-3128] Various loop data viz fixes

data/types.js, package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
[WEB-3219]
Related PRs:
https://github.com/tidepool-org/tideline/pull/446
https://github.com/tidepool-org/blip/pull/1441
[WEB-3219]: https://tidepool.atlassian.net/browse/WEB-3219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3219] Truncate future unknown basal durations

package.json, src/components/daily/bolustooltip/BolusTooltip.js, src/utils/DataUtil.js, test/components/daily/BolusTooltip.test.js, test/utils/DataUtil.test.js
[WEB-3128] [WEB-3225]
Related PR: https://github.com/tidepool-org/blip/pull/1442
[WEB-3128]: https://tidepool.atlassian.net/browse/WEB-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3225]: https://tidepool.atlassian.net/browse/WEB-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3128,WEB-3225] Loop data viz fixes

package.json, src/utils/AggregationUtil.js
[WEB-3230]
Related PR: https://github.com/tidepool-org/blip/pull/1443
[WEB-3230]: https://tidepool.atlassian.net/browse/WEB-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3230] Pdf JS error fix

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
=> Release 1.42.1 to master

data/print/fixtures.js, package.json, src/components/common/controls/ClipboardButton.js, src/modules/print/PrescriptionPrintView.js, src/modules/print/PrintView.js, src/modules/print/index.js, stories/print/PrescriptionPrintPDF.js, test/modules/print/PrescriptionPrintView.test.js, test/modules/print/PrintView.test.js, test/modules/print/index.test.js
[WEB-3110]
Related PR: https://github.com/tidepool-org/blip/pull/1453
[WEB-3110]: https://tidepool.atlassian.net/browse/WEB-3110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3110] Add prescription print view to hotfix release

data/print/fixtures.js, package.json, src/components/common/controls/ClipboardButton.js, src/modules/print/PrescriptionPrintView.js, src/modules/print/PrintView.js, src/modules/print/index.js, stories/print/PrescriptionPrintPDF.js, test/modules/print/PrescriptionPrintView.test.js, test/modules/print/PrintView.test.js, test/modules/print/index.test.js
=> Release 1.42.2 to master

package.json
=> Releasse 1.44.0 to develop

.gitignore, package.json, src/utils/datetime.js, test/utils/datetime.test.js
[WEB-3272] [WEB-3273]
Related PRs:
---
https://github.com/tidepool-org/blip/pull/1485
https://github.com/tidepool-org/platform-client/pull/182
[WEB-3272]: https://tidepool.atlassian.net/browse/WEB-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3273]: https://tidepool.atlassian.net/browse/WEB-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3272,WEB-3273] Clinician-initiated patient data connection

package.json, src/index.js, src/utils/agp/data.js, test/utils/agp/data.test.js
[WEB-3346]
[WEB-3351]
[WEB-3346]: https://tidepool.atlassian.net/browse/WEB-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3351]: https://tidepool.atlassian.net/browse/WEB-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3346, WEB-3351] - CGM Summary Enhancements

package.json, src/components/settings/common/Header.js, test/components/settings/common/Header.test.js
[WEB-3274]
Related PRs
---
https://github.com/tidepool-org/blip/pull/1501
https://github.com/tidepool-org/tideline/pull/448
[WEB-3274]: https://tidepool.atlassian.net/browse/WEB-3274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3274] device settings data sources

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
[WEB-3469]
[WEB-3469]: https://tidepool.atlassian.net/browse/WEB-3469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3469] Abbott device filter label

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
[WEB-3516]
Related PR: 
[WEB-3516]: https://tidepool.atlassian.net/browse/WEB-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3516] Update abbott data connection device name in device list

package.json, src/utils/basal.js, test/utils/basal.test.js
[WEB-3526]
Related PR: https://github.com/tidepool-org/blip/pull/1553
[WEB-3526]: https://tidepool.atlassian.net/browse/WEB-3526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3526] Fix basal dosage calculations for datums that completely encompass the range in view

package.json, src/components/daily/bolustooltip/BolusTooltip.js, src/components/daily/cbgtooltip/CBGTooltip.js, src/modules/print/BasicsPrintView.js, src/modules/print/DailyPrintView.js, src/utils/annotations.js, src/utils/stat.js, test/modules/print/BasicsPrintView.test.js, test/modules/print/DailyPrintView.test.js, test/utils/stat.test.js
[WEB-3564] 
Related PRs:
---
https://github.com/tidepool-org/blip/pull/1559
https://github.com/tidepool-org/tideline/pull/464
[WEB-3564]: https://tidepool.atlassian.net/browse/WEB-3564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3564] Change cgm BG references to Glucose

package.json, src/utils/bolus.js, test/utils/bolus.test.js
[WEB-3399]
Based on feedback from this [discussion thread](https://tidepoolteam.slack.com/archives/CFSURMMS9/p1744769521450649)
I thought i would just simplify the logic down since we don't really need to look at the precision anymore
[WEB-3399]: https://tidepool.atlassian.net/browse/WEB-3399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Override/Underride Calculations

package.json, src/utils/DataUtil.js, test/utils/DataUtil.test.js
[WEB-3631] 
Related PR: https://github.com/tidepool-org/blip/pull/1581
[WEB-3631]: https://tidepool.atlassian.net/browse/WEB-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3631] twiist v3 pump settings

package.json, src/utils/stat.js, test/utils/stat.test.js
[WEB-3002]
[WEB-3002]: https://tidepool.atlassian.net/browse/WEB-3002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEB-3002 - Change wording on tooltip label

package.json, src/utils/format.js, src/utils/stat.js, test/utils/format.test.js, test/utils/stat.test.js
WEB-3501
Blip: https://github.com/tidepool-org/blip/pull/1613
=> WEB-3501 - QA Feedback 1

data/types.js, package.json, src/components/common/tooltips/Tooltip.css, src/utils/DataUtil.js, test/utils/DataUtil.test.js
[WEB-3688]
[WEB-3688]: https://tidepool.atlassian.net/browse/WEB-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3688] Generate suppressed basal data for twiist

package.json, src/utils/AggregationUtil.js
[WEB-3720] 
Related PR: https://github.com/tidepool-org/blip/pull/1637
[WEB-3720]: https://tidepool.atlassian.net/browse/WEB-3720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3720] Ensure that cgm sample interval range is applied in daily print view aggregated data

package.json, src/components/common/tooltips/CgmSampleIntervalTooltip.js
[WEB-3825] 
Related PR: https://github.com/tidepool-org/blip/pull/1669
[WEB-3825]: https://tidepool.atlassian.net/browse/WEB-3825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3825] CGM sample interval label updates

package.json, src/components/common/tooltips/EventsInfoTooltip.js, src/modules/print/DailyPrintView.js
[WEB-3974]
Related PR: https://github.com/tidepool-org/blip/pull/1752
[WEB-3974]: https://tidepool.atlassian.net/browse/WEB-3974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3974] Additional alarm copy changes
